### ISSUE TITLE
Nudge.munki.recipe sets minimum macOS to 11.0, which is incorrect for Nudge 2.0

### ISSUE THREAD

**Issue by robertryansqub** [autopkg/erikng-recipes#13]
The Nudge munki recipe has a hard coded entry for the minimum supported macOS, set to 11.

```
                    <key>minimum_os_version</key>
                    <string>11.0</string>
```

This is, of course, wrong for Nudge 2.0.

**Comment by erikng** [comment]
The munki recipe will still do the right thing because it processes this key in post, but I'll update the recipe.

**Comment by erikng** [comment]
Closing for now as I plan on landing it soon.
