### ISSUE TITLE
Question: Nudge.download.recipe: filename argument 

### ISSUE THREAD

**Issue by joeschlimmer-ic** [autopkg/erikng-recipes#8]
Hey, just curious if there was a particular reason you chose to add the filename argument to the URLDownloader processor in Nudge.download.recipe?

Reason I am asking? I wrote .pkg and .jss recipes to add Nudge to Jamf. My .pkg recipe uses your Nudge.download.recipe as the parent. The download recipe renames Nudge-<version>.pkg to Nudge.pkg. I would like to have the version number in the package name.

I added a PkgCopier processor to my pkg recipe, to rename the download from Nudge.pkg to "%NAME"-%version%.pkg which works fine. I was just curious if there was a specific reason you are renaming Nudge?

Thanks.

**Comment by erikng** [comment]
I'm not sure if this is still a problem, but submit a PR if you need this functionality.
